import logging
from fastapi import FastAPI, Depends, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from typing import List, Dict, Any

from backend.app.database import engine, Base, get_db
from backend.app.config import settings
from backend.app import models, schemas
from backend.app.services.pipeline_generator import generate_pipeline_dag
from backend.app.services.hf_downloader import hf_client
from backend.app.services.executor import PipelineExecutor

# Configure Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[logging.StreamHandler()]
)
logger = logging.getLogger("charvis")

# Initialize Database tables
try:
    logger.info("Initializing database tables...")
    Base.metadata.create_all(bind=engine)
    logger.info("Database tables initialized successfully.")
except Exception as e:
    logger.error(f"Failed to initialize database: {str(e)}")

# Create FastAPI app
app = FastAPI(
    title="Charvis API",
    description="Backend engine for AI Pipeline Generation and Agent Orchestration",
    version="1.0.0"
)

# Set CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Adjust in production for specific domains
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- Background Task Runners ---

def run_pipeline_in_background(execution_id: str, db_session_maker):
    """
    Background worker that executes the pipeline and commits output logs.
    Creates a new database session to avoid thread sharing conflicts.
    """
    db = db_session_maker()
    try:
        executor = PipelineExecutor(db=db, execution_id=execution_id)
        executor.execute()
    except Exception as e:
        logger.error(f"Background execution failed: {str(e)}")
    finally:
        db.close()


def run_model_download_in_background(model_id: str, preferred_quant: str):
    """Background worker to download large GGUF checkpoints."""
    try:
        hf_client.resolve_and_download_gguf(model_id, preferred_quant)
    except Exception as e:
        logger.error(f"Background download failed for '{model_id}': {str(e)}")


# --- REST API Endpoints ---

@app.get("/")
def read_root():
    return {
        "status": "online",
        "app": "Charvis Pipeline Generator & Agent Orchestrator",
        "version": "1.0.0",
        "hf_cache_dir": settings.hf_cache_path
    }


@app.post("/api/pipelines/generate", response_model=schemas.PipelineResponse)
def api_generate_pipeline(payload: schemas.PipelineCreateRequest, db: Session = Depends(get_db)):
    """
    Parses a user's natural language requirement, designs a verified DAG pipeline
    via structured LLM/heuristic drivers, saves the DAG, and returns it.
    """
    logger.info(f"Generating pipeline for prompt: '{payload.prompt}'")
    try:
        dag = generate_pipeline_dag(payload.prompt)
        
        # Save pipeline model to database
        db_pipeline = models.Pipeline(
            title=dag.title,
            description=dag.description,
            user_prompt=payload.prompt,
            dag_json=dag.model_dump()
        )
        db.add(db_pipeline)
        db.commit()
        db.refresh(db_pipeline)
        
        return db_pipeline
    except Exception as e:
        logger.error(f"Failed to generate pipeline: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Generation failed: {str(e)}")


@app.get("/api/pipelines", response_model=List[schemas.PipelineResponse])
def api_list_pipelines(db: Session = Depends(get_db)):
    """Returns a list of all pipelines generated by the user."""
    return db.query(models.Pipeline).order_by(models.Pipeline.created_at.desc()).all()


@app.get("/api/pipelines/{pipeline_id}", response_model=schemas.PipelineResponse)
def api_get_pipeline(pipeline_id: str, db: Session = Depends(get_db)):
    """Retrieves a single pipeline and its executions."""
    pipeline = db.query(models.Pipeline).filter(models.Pipeline.id == pipeline_id).first()
    if not pipeline:
        raise HTTPException(status_code=404, detail="Pipeline not found")
    return pipeline


@app.post("/api/pipelines/{pipeline_id}/execute", response_model=schemas.PipelineExecutionResponse)
def api_execute_pipeline(
    pipeline_id: str,
    payload: schemas.PipelineExecutionRequest,
    background_tasks: BackgroundTasks,
    db: Session = Depends(get_db)
):
    """
    Triggers execution of a pipeline DAG.
    Saves the execution record and offloads runner logic asynchronously
    to a FastAPI background worker thread.
    """
    pipeline = db.query(models.Pipeline).filter(models.Pipeline.id == pipeline_id).first()
    if not pipeline:
        raise HTTPException(status_code=404, detail="Pipeline not found")

    # Verify model cached locally if running in local mode
    if payload.execution_mode == "LOCAL":
        # Loop through nodes and check cached state for their GGUF stubs
        nodes = pipeline.dag_json.get("nodes", [])
        for node in nodes:
            model_id = node.get("model_id")
            if not hf_client.is_model_cached_locally(model_id):
                logger.warning(f"Local run requested but model '{model_id}' is not cached. Downloader fallback will run.")

    # Create new Execution record
    execution = models.PipelineExecution(
        pipeline_id=pipeline_id,
        status="PENDING",
        inputs=payload.inputs,
        execution_mode=payload.execution_mode
    )
    db.add(execution)
    db.commit()
    db.refresh(execution)

    # Queue background runner process
    from backend.app.database import SessionLocal
    background_tasks.add_task(run_pipeline_in_background, execution.id, SessionLocal)
    
    return execution


@app.get("/api/executions/{execution_id}", response_model=schemas.PipelineExecutionResponse)
def api_get_execution(execution_id: str, db: Session = Depends(get_db)):
    """Returns the live status, logs, inputs, and outputs of a pipeline execution."""
    execution = db.query(models.PipelineExecution).filter(models.PipelineExecution.id == execution_id).first()
    if not execution:
        raise HTTPException(status_code=404, detail="Execution record not found")
    return execution


# --- Model Hub Management Endpoints ---

@app.get("/api/models/cache")
def api_get_cached_models():
    """Scans the local HF directory and returns a breakdown of cached repositories."""
    try:
        from huggingface_hub import scan_cache_dir
        cache_info = scan_cache_dir(cache_dir=settings.hf_cache_path)
        cached_repos = []
        for repo in cache_info.repos:
            files = []
            for revision in repo.revisions:
                for file in revision.files:
                    files.append({
                        "filename": file.file_name,
                        "size": file.size,
                        "path": str(file.file_path)
                    })
            cached_repos.append({
                "repo_id": repo.repo_id,
                "repo_type": repo.repo_type,
                "size_on_disk": repo.size_on_disk,
                "size_str": f"{repo.size_on_disk / (1024*1024*1024):.2f} GB",
                "files": files
            })
        return {"cached_dir": settings.hf_cache_path, "repos": cached_repos}
    except Exception as e:
        logger.error(f"Failed to scan cache directory: {str(e)}")
        return {"cached_dir": settings.hf_cache_path, "repos": [], "error": str(e)}


@app.post("/api/models/download")
def api_download_model(
    model_id: str, 
    preferred_quant: str = "q4_k_m", 
    background_tasks: BackgroundTasks = BackgroundTasks()
):
    """Triggers download of a model file in a background worker."""
    if not hf_client.verify_model_exists(model_id):
        raise HTTPException(status_code=400, detail=f"Model '{model_id}' does not exist on the Hugging Face Hub.")

    background_tasks.add_task(run_model_download_in_background, model_id, preferred_quant)
    return {
        "status": "queued",
        "message": f"Background download process initiated for model '{model_id}' targeting quantization format '{preferred_quant}'."
    }
