import datetime
import uuid
from sqlalchemy import Column, String, Text, DateTime, JSON, ForeignKey, Integer
from sqlalchemy.orm import relationship
from backend.app.database import Base

def generate_uuid():
    return str(uuid.uuid4())

class Pipeline(Base):
    __tablename__ = "pipelines"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    user_prompt = Column(Text, nullable=False)
    dag_json = Column(JSON, nullable=False)  # Stores node configuration and connections
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    # Relationships
    executions = relationship("PipelineExecution", back_populates="pipeline", cascade="all, delete-orphan")


class PipelineExecution(Base):
    __tablename__ = "pipeline_executions"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    pipeline_id = Column(String(36), ForeignKey("pipelines.id", ondelete="CASCADE"), nullable=False)
    status = Column(String(50), nullable=False, default="PENDING")  # PENDING, RUNNING, SUCCESS, FAILED
    inputs = Column(JSON, nullable=True)  # Key-value inputs for pipeline parameters
    outputs = Column(JSON, nullable=True) # Pipeline final output results
    execution_mode = Column(String(50), nullable=False, default="SERVERLESS")  # LOCAL, SERVERLESS
    error_message = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    # Relationships
    pipeline = relationship("Pipeline", back_populates="executions")
    node_executions = relationship("NodeExecution", back_populates="execution", cascade="all, delete-orphan")


class NodeExecution(Base):
    __tablename__ = "node_executions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    execution_id = Column(String(36), ForeignKey("pipeline_executions.id", ondelete="CASCADE"), nullable=False)
    node_id = Column(String(100), nullable=False)  # The specific ID of the node in the DAG
    status = Column(String(50), nullable=False, default="PENDING")  # PENDING, RUNNING, SUCCESS, FAILED
    inputs = Column(JSON, nullable=True)  # Inputs passed to this node
    outputs = Column(JSON, nullable=True) # Outputs generated by this node
    logs = Column(Text, nullable=True)     # Detailed thoughts, reasoning steps, tool calls, and stdout
    error_message = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    # Relationships
    execution = relationship("PipelineExecution", back_populates="node_executions")
